export interface PapiQuestion {
  id: number;
  a: string;
  b: string;
}

// PAPI Kostick: 90 pasang pernyataan paksaan-pilihan (forced-choice). Tidak ada jawaban benar/salah.
export const PAPI_QUESTIONS: PapiQuestion[] = [
  { id: 1, a: "Saya seorang pekerja giat", b: "Saya Bukan Seorang Pemurung" },
  { id: 2, a: "Saya suka bekerja lebih baik dari yang lain", b: "Saya melakukan pekerjaan hingga tuntas" },
  { id: 3, a: "Saya suka memberi orang petunjuk bagaimana melakukan sesuatu", b: "Saya senang memberitahukan orang apa yang harus dikerjakan" },
  { id: 4, a: "Saya suka melakukan atau mengatakan hal-hal lucu", b: "Saya senang memberitahukan orang apa yang harus dikerjakan" },
  { id: 5, a: "Saya suka menggabungkan diri dalam kelompok", b: "Saya ingin diperhatikan dalam kelompok" },
  { id: 6, a: "Saya suka Menjalin persahabatan", b: "Saya suka menggabungkan diri dalam suatu kelompok" },
  { id: 7, a: "Jika saya rasa perlu, saya bisa cepat menyesuaikan diri", b: "Saya berusaha Menjalin persahabatan" },
  { id: 8, a: "Saya akan membalas jika saya di sakiti", b: "Saya suka melakukan hal-hal baru dan berbeda" },
  { id: 9, a: "Saya ingin atasan menyukai saya", b: "Saya suka memberitahukan orang jika mereka bersalah" },
  { id: 10, a: "Saya suka mengikuti petunjuk yang di berikan kepada saya", b: "Saya suka membuat atasan senang" },
  { id: 11, a: "Saya berusaha keras sekali", b: "Saya seorang yang rapih" },
  { id: 12, a: "Saya dapat membuat orang melakukan apa yang saya inginkan", b: "Saya tidak mudah marah" },
  { id: 13, a: "Saya suka memberitahu kelompok apa yang harus mereka kerjakan", b: "Saya selalu melakukan pekerjaan sampai tuntas" },
  { id: 14, a: "Saya ingin menjadi orang yang menarik dan mengasyikan", b: "Saya ingin menjadi orang yang sangat berhasil" },
  { id: 15, a: "Saya ingin dapat menyesuaikan diri dengan kelompok-kelompok", b: "Saya suka membantu orang mengambil keputusan" },
  { id: 16, a: "Saya cemas bila seseorang tidak menyukai saya", b: "Saya suka orang memperhatikan saya" },
  { id: 17, a: "Saya suka mencoba hal-hal baru", b: "Saya lebih suka bekerja sama daripada bekerja Sendiri" },
  { id: 18, a: "Kadang-kadang saya menyalahkan orang lain jika ada yang tidak beres", b: "Saya merasa terganggu bila ada yang tidak menyukai saya" },
  { id: 19, a: "Saya suka menyenangkan atasan", b: "Saya suka mencoba pekerjaan-pekerjaan yang baru dan berbeda" },
  { id: 20, a: "Saya menyukai petunjuk-petunjuk yang rinci dalam menyelesaikan pekerjaan", b: "Akan saya katakan kepada orang-orang yang bersangkutan bila mereka menjengkelkan saya" },
  { id: 21, a: "Saya selalu berusaha keras", b: "Saya suka Melaksanakan Setiap langkah dengan hati-hati" },
  { id: 22, a: "Saya akan menjadi seorang pemimpin yang baik", b: "Saya dapat mengorganisir suatu pekerjaan dengan baik" },
  { id: 23, a: "Saya mudah tersinggung", b: "Saya lambat dalam membuat keputusan" },
  { id: 24, a: "Saya suka mengerjakan beberapa pekerjaan sekaligus", b: "Bila saya dalam kelompok, saya lebih sering sebagai pendengar" },
  { id: 25, a: "Saya sangat senang bila mendapat undangan", b: "Saya ingin lebih baik dari yang lain dalam mengerjakan sesuatu" },
  { id: 26, a: "Saya suka Menjalin persahabatan", b: "Saya suka menasehati orang lain" },
  { id: 27, a: "Saya suka melakukan hal-hal baru dan berbeda", b: "Saya suka memberitahu bagaimana saya berhasil dalam melakukan sesuatu" },
  { id: 28, a: "Bila pendapat saya benar, saya akan pertahankan", b: "Saya ingin diterima dan diakui dalam kelompok" },
  { id: 29, a: "Saya tak mau menjadi lain dari yang lain", b: "Saya berusaha dekat dengan orang-orang" },
  { id: 30, a: "Saya senang memberitahu orang bagaimana melakukan suatu pekerjaan", b: "Saya berusaha dekat dengan orang-orang" },
  { id: 31, a: "Saya bekerja keras", b: "Saya banyak berfikir dan membuat perencanaan" },
  { id: 32, a: "Saya memimpin kelompok", b: "Saya tertarik dengan hal-hal yang lebih detail" },
  { id: 33, a: "Saya mengambil Keputusan dengan mudah dan cepat", b: "Saya menyimpan barang-barang dengan rapih dan teratur" },
  { id: 34, a: "Saya melakukan pekerjaan dengan cepat", b: "Saya tidak sering marah atau sedih" },
  { id: 35, a: "Saya ingin menjadi bagian dari kelompok", b: "Saya hanya ingin melakukan pekerjaan pada satu waktu" },
  { id: 36, a: "Saya berusaha Menjalin persahabatan", b: "Saya berusaha keras menjadi yang terbaik" },
  { id: 37, a: "Saya suka mode terbaru untuk pakaian", b: "Saya suka di beri tanggungjawab" },
  { id: 38, a: "Saya menyukai perdebatan", b: "Saya senang mendapat perhatian" },
  { id: 39, a: "Saya suka menyenangkan atasan", b: "Saya tertarik menjadi bagian dalam kelompok" },
  { id: 40, a: "Saya sangat memperhatikan peraturan", b: "Saya ingin orang mengenal saya dengan baik" },
  { id: 41, a: "Saya berusaha keras sekali", b: "Saya sangat ramah" },
  { id: 42, a: "Orang berpendapat saya memimpin dengan baik", b: "Saya berfikir lama dan berhati-hati" },
  { id: 43, a: "Bila ada kesempatan, saya akan memanfaatkannya", b: "Saya senang menangani hal-hal kecil" },
  { id: 44, a: "Orang berpendapat bahwa saya bekerja cepat", b: "Orang berpendapat bahwa saya rapi dan teratur" },
  { id: 45, a: "Saya senang mengikuti pertandingan dan berolahraga", b: "Saya memiliki kepribadian yang menyenangkan" },
  { id: 46, a: "Saya senang jika orang dekat dan bersahabat dengan saya", b: "Saya selalu berusaha menyelesaikan sesuatu yang telah saya mulai" },
  { id: 47, a: "Saya senang bereksperimen dan mencoba hal-hal baru", b: "Saya suka mengerjakan pekerjaan yang sulit-sulit" },
  { id: 48, a: "Saya suka diperlakukan dengan adil", b: "Saya suka memberitahu orang lain bagaimana Melaksanakan sesuatu" },
  { id: 49, a: "Saya suka melakukan apa yang diharapkan orang dari saya", b: "Saya suka jika orang perduli terhadap saya" },
  { id: 50, a: "Saya suka diterangkan tugas saya sedetail-detailnya", b: "Saya senang berada bersama orang-orang" },
  { id: 51, a: "Saya selalu berusaha menyelesaikan pekerjaan dengan sempurna", b: "Orang mengatakan bahwa saya hampir-hampir tidak pernah lelah" },
  { id: 52, a: "Saya tipe pemimpin", b: "Saya mudah bergaul" },
  { id: 53, a: "Saya gunakan kesempatan", b: "Saya banyak sekali berfikir" },
  { id: 54, a: "Saya bekerja dengan tempo yang tinggi dan mantap", b: "Saya senang menangani detail suatu pekerjaan" },
  { id: 55, a: "Saya memiliki banyak tenaga untuk kegiatan dan berolah raga", b: "Saya mengatur dan menyimpan barang dengan teratur dan rapi" },
  { id: 56, a: "Saya dapat bergaul baik dengan semua orang", b: "Saya orang yang berwatak tenang" },
  { id: 57, a: "Saya ingin bertemu dengan orang-orang baru dan melakukan hal-hal baru", b: "Saya selalu ingin menyelesaikan pekerjaan yang telah saya mulai" },
  { id: 58, a: "Saya biasanya mempertahankan pendapat yang saya yakini", b: "Saya biasanya suka bekerja keras" },
  { id: 59, a: "Saya menyambut baik saran-saran dari orang yang saya kagumi", b: "Saya suka bertanggung jawab terhadap orang lain" },
  { id: 60, a: "Saya membiarkan diri saya dipengaruhi dengan kuat oleh orang lain", b: "Saya senang bila memperoleh banyak perhatian" },
  { id: 61, a: "Biasanya saya bekerja keras sekali", b: "Biasanya saya bekerja cepat" },
  { id: 62, a: "Apabila saya bicara, kelompok diam dan mendengarkan", b: "Saya trampil menggunakan perkakas" },
  { id: 63, a: "Saya lambat dalam membuat persahabatan", b: "Saya lambat dalam mengambil Keputusan" },
  { id: 64, a: "Biasanya saya makan dengan cepat", b: "Saya suka membaca" },
  { id: 65, a: "Saya suka pekerjaan Dimana saya banyak bergerak", b: "Saya suka pekerjaan yang harus dilaksanakan dengan hati-hati" },
  { id: 66, a: "Saya mudah membuat sebanyak mungkin teman", b: "Saya mudah menemukan kembali barang-barang yang saya simpan" },
  { id: 67, a: "Saya membuat rencana jauh-jauh sebelumnya", b: "Saya selalu menyenangkan" },
  { id: 68, a: "Saya menjunjung tinggi nama baik saya", b: "Saya terus menekuni suatu masalah sampai tuntas" },
  { id: 69, a: "Saya suka menyenangkan orang-orang yang saya kagumi", b: "Saya ingin sukses" },
  { id: 70, a: "Saya suka orang lain mengambil Keputusan untuk kelompok", b: "Saya suka mengambil Keputusan untuk kelompok" },
  { id: 71, a: "Saya selalu berusaha keras", b: "Saya mengambil Keputusan secara cepat dan mudah" },
  { id: 72, a: "Kelompok biasanya melakukan apa yang saya inginkan", b: "Saya biasanya bekerja cepat-cepat" },
  { id: 73, a: "Saya sering merasa lelah", b: "Saya lambat dalam mengambil Keputusan" },
  { id: 74, a: "Saya bekerja cepat", b: "Saya mudah berteman" },
  { id: 75, a: "Saya biasanya mempunyai gairah dan tenaga", b: "Saya banyak menghabiskan waktu untuk berfikir" },
  { id: 76, a: "Saya sangat ramah terhadap orang", b: "Saya suka pekerjaan yang memerlukan ketelitian" },
  { id: 77, a: "Saya banyak berfikir dan membuat perencanaan", b: "Saya menyimpan sesuatu pada tempatnya" },
  { id: 78, a: "Saya suka pekerjaan yang menuntut perhatian terhadap hal detail", b: "Saya tidak mudah marah" },
  { id: 79, a: "Saya suka menuruti orang yang saya kagumi", b: "Saya selalu menyelesaikan pekerjaan yang saya telah saya mulai" },
  { id: 80, a: "Saya suka petunjuk-petunjuk yang jelas", b: "Saya suka bekerja keras" },
  { id: 81, a: "Saya mengejar apa yang saya inginkan", b: "Saya seorang pemimpin yang baik" },
  { id: 82, a: "Saya dapat membuat orang lain bekerja keras", b: "Saya adalah type orang yang tak kenal susah" },
  { id: 83, a: "Saya mengambil Keputusan dengan cepat", b: "Saya bicara dengan cepat" },
  { id: 84, a: "Rasanya saya bekerja secara tergesa-gesa", b: "Saya berolah raga secara teratur" },
  { id: 85, a: "Saya tidak suka bertemu kebanyakan orang", b: "Saya cepat merasa lelah" },
  { id: 86, a: "Saya mempunyai banyak sekali teman", b: "Saya banyak menghabiskan waktu untuk berfikir" },
  { id: 87, a: "Saya suka bekerja dengan teori", b: "Saya suka menangani detail suatu pekerjaan" },
  { id: 88, a: "Saya suka menangani detail suatu pekerjaan", b: "Saya Suka mengorganisir pekerjaan saya" },
  { id: 89, a: "Saya menaruh barang pada tempatnya", b: "Saya selalu menyenangkan" },
  { id: 90, a: "Saya suka diberitahu apa yang perlu saya kerjakan", b: "Saya harus menyelesaikan pekerjaan yang telah saya mulai" },
];
