import { Question } from "@/lib/types/hexaco";

export const HEXACO_QUESTIONS: Question[] = [
  { id: 1, text: "Saya akan cukup bosan ketika mengunjungi sebuah pameran seni.", reverse: true },
  { id: 2, text: "Saya cukup sering membersihkan kantor atau rumah saya.", reverse: false },
  { id: 3, text: "Saya jarang menyimpan dendam, bahkan terhadap mereka yang telah menyakitiku.", reverse: false },
  { id: 4, text: "Saya merasa cukup puas dengan keadaan diri saya secara keseluruhan.", reverse: false },
  { id: 5, text: "Saya akan merasa takut jika harus bepergian dalam cuaca yang buruk.", reverse: false },
  { id: 6, text: "Saya akan memperlakukan orang yang tidak saya sukai dengan sangat baik jika saya menginginkan sesuatu darinya.", reverse: true },
  { id: 7, text: "Saya tertarik untuk mempelajari sejarah dan politik negara-negara lain.", reverse: false },
  { id: 8, text: "Saya sering membuat target-target ambisius untuk diri sendiri dalam bekerja.", reverse: false },
  { id: 9, text: "Terkadang orang mengatakan bahwa saya terlalu suka mengkritik orang lain.", reverse: true },
  { id: 10, text: "Saya jarang mengemukakan pendapat dalam diskusi atau rapat.", reverse: true },
  { id: 11, text: "Terkadang saya tidak bisa untuk tidak mengkhawatirkan hal-hal sepele.", reverse: false },
  { id: 12, text: "Seandainya saya tahu saya tidak akan pernah tertangkap, saya akan bersedia mencuri milyaran rupiah.", reverse: true },
  { id: 13, text: "Saya menginginkan pekerjaan yang harus mengikuti rutinitas daripada pekerjaan yang membutuhkan kreatifitas.", reverse: true },
  { id: 14, text: "Saya sering berkali-kali memeriksa pekerjaan saya agar tidak ada kesalahan yang terlewat.", reverse: false },
  { id: 15, text: "Terkadang orang mengatakan bahwa saya terlalu keras kepala.", reverse: true },
  { id: 16, text: "Saya menghindari berbasa-basi dengan orang lain.", reverse: true },
  { id: 17, text: "Saya butuh seseorang untuk menghibur saya ketika mengalami kejadian yang menyakitkan.", reverse: false },
  { id: 18, text: "Memiliki banyak uang bukanlah hal yang terlalu penting bagi saya.", reverse: false },
  { id: 19, text: "Saya rasa memperhatikan ide-ide baru yang sangat tidak biasa itu membuang-buang waktu.", reverse: true },
  { id: 20, text: "Saya membuat keputusan berdasarkan suasana hati daripada pertimbangan matang.", reverse: true },
  { id: 21, text: "Orang lain menganggap saya adalah orang yang cepat marah.", reverse: true },
  { id: 22, text: "Saya hampir setiap saat penuh dengan semangat.", reverse: false },
  { id: 23, text: "Saya jadi ingin menangis ketika melihat orang lain menangis.", reverse: false },
  { id: 24, text: "Saya adalah orang biasa yang tidak lebih baik dari orang lain.", reverse: false },
  { id: 25, text: "Saya tidak akan menghabiskan waktu saya membaca sebuah buku puisi.", reverse: true },
  { id: 26, text: "Saya membuat rencana dan mengatur segala sesuatu sedemikian rupa agar tidak kelabakan di saat-saat terakhir.", reverse: false },
  { id: 27, text: "Sikap saya terhadap mereka yang telah memperlakukan saya dengan buruk adalah “maafkan dan lupakan”.", reverse: false },
  { id: 28, text: "Ada beberapa hal dalam kepribadian saya yang saya rasa disukai oleh kebanyakan orang.", reverse: false },
  { id: 29, text: "Saya tidak keberatan melakukan pekerjaan yang berbahaya.", reverse: true },
  { id: 30, text: "Saya tidak akan menggunakan sanjungan untuk mendapatkan kenaikan gaji atau pangkat di tempat kerja, bahkan jika saya kira itu akan berhasil.", reverse: false },
  { id: 31, text: "Saya suka memperhatikan peta dari berbagai tempat.", reverse: false },
  { id: 32, text: "Saya sering berusaha sangat keras untuk dapat mencapai target yang saya inginkan.", reverse: false },
  { id: 33, text: "Saya biasanya menerima kesalahan orang lain tanpa mengeluhkannya.", reverse: false },
  { id: 34, text: "Dalam pertemuan sosial, saya biasanya berinisiatif untuk memulai pembicaraan dengan orang lain.", reverse: false },
  { id: 35, text: "Dibandingkan kebanyakan orang, saya sangat jarang merasa khawatir.", reverse: true },
  { id: 36, text: "Saya akan tergoda untuk membeli barang curian jika saya sedang kesulitan keuangan.", reverse: true },
  { id: 37, text: "Saya akan menikmati menciptakan karya seni, seperti novel, lagu, atau lukisan.", reverse: false },
  { id: 38, text: "Ketika mengerjakan sesuatu, saya tidak terlalu memperhatikan hal-hal kecil.", reverse: true },
  { id: 39, text: "Saat orang tidak setuju dengan pendapat saya, saya biasanya cukup fleksibel untuk menerimanya.", reverse: false },
  { id: 40, text: "Saya suka berkumpul dengan banyak orang dan berbincang dengan mereka.", reverse: false },
  { id: 41, text: "Saya dapat mengatasi situasi sulit tanpa perlu dukungan moral dari orang lain.", reverse: true },
  { id: 42, text: "Saya ingin tinggal di perumahan mahal tempat orang-orang kaya tinggal.", reverse: true },
  { id: 43, text: "Saya suka orang yang memiliki pandangan tidak konvensional.", reverse: false },
  { id: 44, text: "Saya melakukan banyak kesalahan karena saya tidak berpikir sebelum bertindak.", reverse: true },
  { id: 45, text: "Saya tidak mudah marah, bahkan saat orang-orang memperlakukan saya dengan agak buruk.", reverse: false },
  { id: 46, text: "Hampir setiap hari saya merasa ceria dan optimis.", reverse: false },
  { id: 47, text: "Ketika orang dekat saya merasa sedih, saya hampir seperti dapat merasakan kesedihan mereka.", reverse: false },
  { id: 48, text: "Saya tidak ingin orang lain memperlakukan saya seolah-olah status saya lebih tinggi dari pada mereka.", reverse: false },
  { id: 49, text: "Seandainya saja saat ini saya punya kesempatan, saya mau datang ke sebuah konser musik.", reverse: false },
  { id: 50, text: "Kamar atau meja saya yang berantakan sering kali menjadi bahan lelucon bagi orang lain.", reverse: true },
  { id: 51, text: "Kalau seseorang sudah mencurangi saya sekali, saya akan selalu mencurigai orang tersebut.", reverse: true },
  { id: 52, text: "Saya merasa saya adalah orang yang tidak populer.", reverse: true },
  { id: 53, text: "Saya sangat takut saat berhadapan dengan bahaya yang mengancam fisik saya.", reverse: false },
  { id: 54, text: "Kalau saya menginginkan sesuatu dari seseorang, lelucon tidak lucu dari orang tersebut pun akan saya tertawakan.", reverse: true },
  { id: 55, text: "Saya akan sangat bosan ketika membaca buku tentang sejarah ilmu pengetahuan dan teknologi.", reverse: true },
  { id: 56, text: "Saya sering menyerah di tengah jalan sebelum mencapai target yang saya tetapkan.", reverse: true },
  { id: 57, text: "Saya cenderung bersikap lunak dalam menilai orang lain.", reverse: false },
  { id: 58, text: "Ketika berada dalam sebuah kelompok, saya sering menjadi seseorang yang berbicara mewakili kelompok tersebut.", reverse: false },
  { id: 59, text: "Saya jarang sekali, kalaupun pernah, sulit tidur karena stres atau cemas.", reverse: true },
  { id: 60, text: "Saya tidak akan pernah menerima suap, bahkan jika  jumlahnya sangat besar sekalipun.", reverse: false },
  { id: 61, text: "Orang lain sering mengatakan bahwa saya memiliki imajinasi yang bagus.", reverse: false },
  { id: 62, text: "Saya selalu berusaha untuk akurat dalam bekerja, meskipun itu memakan banyak waktu.", reverse: false },
  { id: 63, text: "Ketika orang lain mengatakan bahwa saya salah, reaksi pertama saya adalah membantah mereka.", reverse: true },
  { id: 64, text: "Saya lebih suka pekerjaan yang harus banyak berinteraksi dengan orang lain daripada yang harus bekerja sendiri.", reverse: false },
  { id: 65, text: "Kapanpun saya mengkhawatirkan sesuatu, saya ingin menceritakan kekhawatiran saya kepada orang lain.", reverse: false },
  { id: 66, text: "Saya ingin dilihat orang sedang mengendarai mobil yang sangat mahal.", reverse: true },
  { id: 67, text: "Saya menganggap diri saya sebagai seorang yang agak eksentrik.", reverse: false },
  { id: 68, text: "Saya tidak mengizinkan keinginan sesaat mengendalikan tingkah laku saya.", reverse: false },
  { id: 69, text: "Kebanyakan orang cenderung lebih mudah marah daripada saya.", reverse: false },
  { id: 70, text: "Orang lain sering menganjurkan saya untuk berusaha menjadi lebih ceria.", reverse: true },
  { id: 71, text: "Saya merasa sangat kehilangan ketika orang dekat saya pergi untuk waktu yang lama.", reverse: false },
  { id: 72, text: "Saya merasa seharusnya saya lebih dihormati dibandingkan orang kebanyakan.", reverse: true },
  { id: 73, text: "Terkadang saya suka untuk hanya duduk dan melihat angin berhembus di sela-sela pepohonan.", reverse: false },
  { id: 74, text: "Saya kadang mengalami kesulitan dalam bekerja karena ketidakrapian saya.", reverse: true },
  { id: 75, text: "Sulit bagi saya untuk benar-benar memaafkan seseorang yang telah menyakiti saya.", reverse: true },
  { id: 76, text: "Kadang saya merasa saya ini orang yang tidak berguna.", reverse: true },
  { id: 77, text: "Saya tidak akan merasa panik meskipun dalam situasi genting.", reverse: true },
  { id: 78, text: "Saya tidak akan berpura-pura menyukai seseorang hanya agar dia mau membantu saya.", reverse: false },
  { id: 79, text: "Saya tidak pernah benar-benar menikmati membaca ensiklopedia.", reverse: true },
  { id: 80, text: "Saya hanya melakukan usaha minimum yang dibutuhkan untuk menyelesaikan pekerjaan saya.", reverse: true },
  { id: 81, text: "Bahkan saat seseorang melakukan banyak kesalahan, saya jarang mengomel atau menggerutu.", reverse: false },
  { id: 82, text: "Saya cenderung merasa agak canggung ketika berbicara di depan umum.", reverse: true },
  { id: 83, text: "Saya merasa sangat cemas saat menunggu sebuah pengumuman penting.", reverse: false },
  { id: 84, text: "Saya akan tergoda untuk menggunakan uang palsu, jika saya yakin tidak akan ketahuan.", reverse: true },
  { id: 85, text: "Saya tidak menganggap diri saya sebagai seorang yang artistik ataupun kreatif.", reverse: true },
  { id: 86, text: "Orang sering menyebut saya sebagai seorang perfeksionis.", reverse: false },
  { id: 87, text: "Sulit bagi saya untuk berkompromi dengan orang lain ketika saya sangat yakin bahwa saya benar.", reverse: true },
  { id: 88, text: "Hal pertama yang selalu saya lakukan di tempat baru adalah mencari teman baru.", reverse: false },
  { id: 89, text: "Saya jarang menceritakan masalah saya kepada orang lain.", reverse: true },
  { id: 90, text: "Saya akan mendapatkan banyak kepuasan dari memiliki barang-barang mewah yang mahal.", reverse: true },
  { id: 91, text: "Bagi saya, diskusi filosofis itu membosankan.", reverse: true },
  { id: 92, text: "Saya lebih memilih untuk bertindak spontan daripada mengikuti rencana.", reverse: true },
  { id: 93, text: "Sulit bagi saya menahan amarah saat orang lain menghina saya.", reverse: true },
  { id: 94, text: "Kebanyakan orang lebih lincah dan dinamis dibandingkan saya.", reverse: true },
  { id: 95, text: "Saya tetap tidak merasakan apapun meskipun berada dalam situasi yang membuat banyak orang menjadi sangat sentimental.", reverse: true },
  { id: 96, text: "Saya ingin orang-orang tahu bahwa saya ini orang penting berstatus tinggi.", reverse: true },
  { id: 97, text: "Saya bersimpati kepada orang yang kurang beruntung dibanding saya.", reverse: false },
  { id: 98, text: "Saya berusaha untuk banyak memberi pada mereka yang membutuhkan.", reverse: false },
  { id: 99, text: "Tidak masalah bagi saya untuk menyakiti seseorang yang tidak kusukai.", reverse: true },
  { id: 100, text: "Orang menganggap saya sebagai seorang yang tidak berperasaan.", reverse: true },
];

if (HEXACO_QUESTIONS.length !== 100) {
  throw new Error("Bank soal HEXACO harus berisi tepat 100 soal.");
}

// Alias kompatibilitas untuk komponen aplikasi.
export const questions = HEXACO_QUESTIONS;

